config/routes.rb
Rails.application.routes.draw do
  resources :records
  get 'home/index'
  # Defines the root path route ("/")
  root to: "home#index"

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations"
  }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :records
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name, :position])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @check_records = verify_record
    @current_record = @check_records.first if @check_records
  end

  private

  def verify_record
    Record.where(user_id: current_user.id, reference_day: Date.today )
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  

  # GET /records or /records.json
  def index
    @records = Record.where(user_id: current_user.id)
  end

  # GET /records/1 or /records/1.json
  def show
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records or /records.json
  def create
    @record = Record.new(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to home_index_path, notice: "Record was successfully created." }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1 or /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to record_url(@record), notice: "Record was successfully updated." }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1 or /records/1.json
  def destroy
    @record.destroy

    respond_to do |format|
      format.html { redirect_to records_url, notice: "Record was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def record_params
      params.require(:record).permit(:checkin, :checkout, :lunch_start, :lunch_end, :observations, :user_id)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name, :position])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :name, :position])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    home_index_path
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :authenticate_user!

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :name, :position])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/home/index.html.erb
<div class="container-fluid text-center">
    <% if user_signed_in? %>
        <h2>WELCOME, <%=current_user.name %> !!!</h2>     
        <div class="card">
            <div class="card-body">
                The recorded information is monitored in real time, so always keep it up to date.
            </div>
        </div> 
        <div>
            <div class="btn-group p-3" role="group" aria-label="Basic mixed styles example">
                <%= link_to "HISTORY", records_path, class: "btn btn-primary btn-lg" %>
                <% if @check_records.exists? %> 
                    <%= link_to "ATUALIZAR", edit_record_path(@current_record.id), class: "btn btn-warning btn-lg" %>
                <% else %>
                    <%= link_to "TIME REGISTER", new_record_path, class: "btn btn-warning btn-lg" %>
                <% end %>
                <%= link_to "LOGOUT", destroy_user_session_path(@user), method: "delete", class: "btn btn-danger btn-lg" %>
            </div>
        </div>
    <% else %>
        <h1>Time Register System</h1>
        <img src="https://912784.smushcdn.com/2239677/wp-content/uploads/2020/07/Banco-de-Horas-com-Compensa%C3%A7%C3%A3o-da-Dom%C3%A9stica-como-funciona-1-768x486.jpg?lossy=1&strip=1&webp=1" alt="rss feed" width="30%" />
        <div class="text-muted">
            <%= link_to "LOGIN", new_user_session_path, class: "btn btn-sm btn-primary m-2" %>
            <hr>
            <small>Don't have an account? <%= link_to "SIGN UP", new_user_registration_path %> </small> 
        </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="collapse" id="navbarToggleExternalContent">
      <div class="bg-dark p-4">
        <h5 class="text-white h4">Collapsed content</h5>
        <span class="text-muted">Toggleable via the navbar brand.</span>
      </div>
    </div>
    <nav class="navbar navbar-dark bg-dark">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/records/_form.html.erb
<%= form_with(model: record) do |form| %>
  <% if record.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
        <% record.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :checkin, style: "display: block" %>
    <%= form.time_field :checkin, id:'checkin' %>
  </div>
  
  <div>
    <%= form.label :lunch_start, style: "display: block" %>
    <%= form.time_field :lunch_start %>
  </div>
  
  <div>
    <%= form.label :lunch_end, style: "display: block" %>
    <%= form.time_field :lunch_end %>
  </div>
  
  <div>
    <%= form.label :checkout, style: "display: block" %>
    <%= form.time_field :checkout, value: Time.now %>
  </div>
  
  <div>
    <%= form.label :observations, style: "display: block" %>
    <%= form.text_area :observations %>
  </div>
  
  <div>
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>
  
  <div>
    <%= form.submit "RECORD TIME", class:"btn btn-primary" %>
  </div>
<% end %>

<script>
  
</scrip>

app/views/records/_record.html.erb
<div id="<%= dom_id record %>">
  <p>
    <strong>Checkin:</strong>
    <%= record.checkin %>
  </p>

  <p>
    <strong>Checkout:</strong>
    <%= record.checkout %>
  </p>

  <p>
    <strong>Lunch start:</strong>
    <%= record.lunch_start %>
  </p>

  <p>
    <strong>Lunch end:</strong>
    <%= record.lunch_end %>
  </p>

  <p>
    <strong>Observations:</strong>
    <%= record.observations %>
  </p>

</div>

app/views/records/edit.html.erb
<div class="card text-center" style="width: 50%; margin: 0 auto">
  <div class="card-header">
    <h2>Editing record</h2>
  </div>
  <%= render "form", record: @record %>

  <br>

  <div>
    <%= link_to "Show this record", @record %> |
    <%= link_to "Back to records", records_path %>
  </div>
</div>

app/views/records/index.html.erb
<div class="card text-center" style="width: 50%; margin: 0 auto">
  <div class="card-header">
    <h2>Records by <%= @records.first.user.name %></h2>
  </div>
  
  <p style="color: green"><%= notice %></p>

  <div id="records">
    <% @records.each do |record| %>
      <%= render record %>
    <% end %>
  </div>

  <%= link_to "BANK TO HOMEPAGE", home_index_path %>
</div

app/views/records/new.html.erb
<div class="card text-center" style="width: 50%; margin: 0 auto">
  <div class="card-header">
    <h2>Record  (<%= Date.today %>) </h2>
  </div>

  <%= render "form", record: @record %>

  <br>

  <div>
    <%= link_to "Back to records", records_path %>
  </div>
</div>

app/views/records/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @record %>

<div>
  <%= link_to "Edit this record", edit_record_path(@record) %> |
  <%= link_to "Back to records", records_path %>

  <%= button_to "Destroy this record", @record, method: :delete %>
</div>